# Generated by Django 4.0.4 on 2022-08-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
