# Generated by Django 4.0.4 on 2022-08-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_dislike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislike',
            new_name='dislikes',
        ),
    ]
